saleor/blog/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views
from .views import PostListView, PostDetailView, PostListByTagView

urlpatterns = [
    url(r'^(page(?P<page>\d+)/)?$', PostListView.as_view(), name='post-list'),
    url(r'^tags/(?P<slug>[-\w]+)/(page(?P<page>\d+)/)?$',
        PostListByTagView.as_view(), name='post-list-by-tag'),
    url(r'^archive/$', views.post_archive, name='post-archive'),
    url(r'^(?P<slug>[-\w]+)/$', PostDetailView.as_view(), name='post-detail'),
]

saleor/saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import JavaScriptCatalog, set_language

from .account.urls import urlpatterns as account_urls
from .checkout.urls import (
    cart_urlpatterns as cart_urls, checkout_urlpatterns as checkout_urls)
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .graphql.api import schema
from .graphql.views import GraphQLView
from .order.urls import urlpatterns as order_urls
from .page.urls import urlpatterns as page_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

non_translatable_urlpatterns = [
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql/', csrf_exempt(GraphQLView.as_view(
        schema=schema)), name='api'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^i18n/$', set_language, name='set_language'),
    url('', include('social_django.urls', namespace='social'))]

translatable_urlpatterns = [
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^contact/', include(('contact.urls','contact'), namespace='contact')),
    url(r'^blog/', include(('blog.urls','blog'), namespace='blog')),
    url(r'', include(('core1.urls', 'core1'), namespace='core')),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^page/', include((page_urls, 'page'), namespace='page')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search'))]

urlpatterns = non_translatable_urlpatterns + i18n_patterns(
    *translatable_urlpatterns)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
        # static files (images, css, javascript, etc.)
        url(r'^static/(?P<path>.*)$', serve)] + static(
            '/media/', document_root=settings.MEDIA_ROOT)

if settings.ENABLE_SILK:
    urlpatterns += [
        url(r'^silk/', include('silk.urls', namespace='silk'))]

saleor/blog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.conf import settings


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class PostQuerySet(models.QuerySet):
    def active(self):
        return self.filter(status__in=[Post.STATUS_PUBLISHED, Post.STATUS_ARCHIVED])

    def published(self):
        return self.filter(status=Post.STATUS_PUBLISHED)


class Post(models.Model):
    STATUS_DRAFT = 1
    STATUS_PUBLISHED = 2
    STATUS_ARCHIVED = 3
    STATUSES = (
        (STATUS_DRAFT, 'Draft'),
        (STATUS_PUBLISHED, 'Published'),
        (STATUS_ARCHIVED, 'Archived'),
    )

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=255, unique=True)
    body = models.TextField()
    snippet = models.TextField()
    tags = models.ManyToManyField(Tag, blank=True)
    status = models.SmallIntegerField(choices=STATUSES)
    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(blank=True, null=True)
    published_date = models.DateTimeField(blank=True, null=True)

    objects = PostQuerySet.as_manager()

    class Meta:
        ordering = ('-created_date',)

    def __str__(self):
        return self.title

saleor/blog/views.py
# -*- coding: utf-8 -*-

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.shortcuts import render
from django.utils import dateformat

from .models import Post, Tag


class PostListView(ListView):
    queryset = Post.objects.published()
    context_object_name = 'posts'


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'


class PostListByTagView(ListView):
    context_object_name = 'posts'
    allow_empty = False
    template_name_suffix = '_list_by_tag'

    def get_queryset(self):
        return Post.objects.active().filter(tags__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(PostListByTagView, self).get_context_data(**kwargs)
        context['tag'] = Tag.objects.get(slug=self.kwargs['slug'])
        return context


def post_archive(request):
    posts = Post.objects.active()
    years = {}
    for post in posts:
        year = dateformat.format(post.published_date, 'Y')
        if year not in years:
            years[year] = [post]
        else:
            years[year].append(post)
    return render(request, 'blog/post_archive.html', {'years': years})

saleor/templates/blog/base.html
{% extends 'base1.html' %}

{% block title %}Blog &middot; {{ block.super }}{% endblock %}

{% block content-wrapper %}
  <div class="row">
    <div class="col-md-9">
      <div class="blog">
        {% block content %}{% endblock %}
      </div>
    </div>

<div class="col-md-3 col-sm-5">
      {% block sidebar-right %}
       <div class="sidebar-item categories">
          <h3>Browse</h3>

          <ul class="nav navbar-stacked">
            <li><a href="{% url 'blog:post-archive' %}">Archive</a></li>
            <li><a href="{% url 'blog:post-archive' %}">2017</a></li>
            <li><a href="{% url 'blog:post-archive' %}">2018</a></li>
            <li><a href="{% url 'blog:post-archive' %}">2019</a></li>
          <ul>
        </div>

        {% if post_tags %}
<div class="sidebar-item tag-cloud">
            <h3>Tags</h3>

            <ul class="nav nav-pills">
              {% for post_tag in post_tags %}
                <li><a href="{% url 'blog:post-list-by-tag' post_tag.slug %}">{{ post_tag.name }}</a></li>
              {% endfor %}
            <ul>
          </div>
        {% endif %}
      {% endblock %}
    </div>
  </div>
{% endblock %}
                

saleor/templates/blog/post_archive.html
{% extends 'blog/base.html' %}

{% block title %}Archive &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <li><a href="{% url 'blog:post-list' %}">Blog</a></li>
  <li class="active">Archive</li>
{% endblock %}

{% block content %}
  <div class="post-archive">
    <h1>Archive</h1>

    {% for year, posts in years.items %}
      <h3>{{ year }}</h3>

      <ul>
        {% for post in posts %}
          <li>
            <div class="date">
              {{ post.published_date|date:"M d" }}
            </div>

            <a href="{% url 'blog:post-detail' slug=post.slug %}">{{ post.title }}</a>
          </li>
        {% endfor %}
      </ul>
    {% empty %}
      <p>No posts yet.</p>
    {% endfor %}
  </div>
{% endblock content %}

saleor/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}{{ post.title }} &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <li><a href="{% url 'blog:post-list' %}">Blog</a></li>
  <li class="active">{{ post.title }}</li>
{% endblock %}

{% block content %}
    <section id="blog-details" class="padding-top">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-7">
                    <div class="row">
                         <div class="col-md-12 col-sm-12">
                            <div class="single-blog blog-details two-column">
                                <div class="post-thumb">
                                    <a href="#"><img src="images/blog/7.jpg" class="img-responsive" alt=""></a>
                                    <div class="post-overlay">
                                        <span class="uppercase"><a href="#">{{ post.published_date|date:"F j, Y" }}</a></span>
                                    </div>
                                </div>
                                <div class="post-content overflow">
                                    <h2 class="post-title bold"><a href="#">{{ post.title }}</a></h2>
                                    <p>{{ post.body|safe }}</p>
                                    <div class="blog-share">
                                        <span class='st_facebook_hcount'></span>
                                        <span class='st_twitter_hcount'></span>
                                        <span class='st_linkedin_hcount'></span>
                                        <span class='st_pinterest_hcount'></span>
                                        <span class='st_email_hcount'></span>
                                    </div>
                                    <div class="author-profile padding">
                                        <div class="row">
                                            <div class="col-sm-2">
                                                <img src="images/blogdetails/1.png" alt="">
                                            </div>
                                            <div class="col-sm-10">
                                                <h3>Rodrix Hasel</h3>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliq Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi</p>
                                                <span>Website:<a href="www.jooomshaper.com"> www.jooomshaper.com</a></span>
                                            </div>
                                        </div>
                                    </div>
                                        {% if post.tags.all %}
      <div class="tags">
        {% for tag in post.tags.all %}
          <a href="{% url 'blog:post-list-by-tag' tag.slug %}" class="btn btn-info btn-xs">{{ tag.name }}</a>
        {% endfor %}
      </div>
    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                 </div>
              </div>
            </div>
    </section>
    <!--/#blog-->

{% endblock %}

saleor/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %} 

{% block breadcrumbs %}
  {{ block.super }}
    <section id="page-breadcrumb">
        <div class="vertical-center sun">
             <div class="container">
                <div class="row">
                    <div class="action">
                        <div class="col-sm-12">
                            <h1 class="title">Blog</h1>
                            <p>Timeline</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/#page-breadcrumb-->
{% endblock %}

{% block content %}

 <section id="blog" class="padding-top">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-5">
                </div>
                {% for post in posts %}
                <div class="col-md-6 col-sm-7">
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="single-blog two-column">
                                <div class="post-thumb">
                                    <a href="blogdetails.html"><img src="images/blog/9.jpg" class="img-responsive" alt=""></a>
                                    <div class="post-overlay">
                                        <span class="uppercase"><a href="#">{{ post.published_date|date:"F j, Y" }}</a></span>
                                    </div>
                                </div>
                                <div class="post-content overflow">
                                    <h2 class="post-title bold"><a href="{% url 'blog:post-detail' slug=post.slug %}">{{ post.title }}</a></h2>
                                    <p>{{ post.snippet|safe }}</p>
                                    <a href="{% url 'blog:post-detail' slug=post.slug %}">Read more &rarr;</a>
                                    <div class="post-bottom overflow">
                                        <ul class="nav navbar-nav post-nav">
                                            <li><a href="#"></a></li>
                                            <li><a href="#"></a></li>
                                            <li><a href="#"></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% empty %}
    <h1>Blog</h1>
                      {% endfor %}
    <p>No More posts yet.</p>

                    {% include 'core/includes/_pagination.html' with url_name='blog:post-list' %}
                 </div>
            </div>
        </div>
    </section>
    {% endblock content %}

    <!--/#blog-->



























    <div class="post">
      <h2></h2>

      <div class="date">
        <span class="glyphicon glyphicon-time"></span>
        
      </div>

      

      
    </div>
  

saleor/templates/blog/post_list_by_tag.html
{% extends 'blog/base.html' %}

{% block title %}{{ tag.name }} &middot; Tags &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
  {{ block.super }}
  <li><a href="{% url 'blog:post-list' %}">Blog</a></li>
  <li>Tags</li>
  <li class="active">{{ tag.name }}</li>
{% endblock %}

{% block content %}
  {% for post in posts %}
    <div class="post">
      <h2><a href="{% url 'blog:post-detail' slug=post.slug %}">{{ post.title }}</a></h2>

      <div class="date">
        <span class="glyphicon glyphicon-time"></span>
        {{ post.published_date|date:"F j, Y" }}
      </div>

      <p>{{ post.snippet|safe }}</p>

      <a href="{% url 'blog:post-detail' slug=post.slug %}">Read more &rarr;</a>
    </div>
  {% endfor %}

  {% include 'core/includes/_pagination.html' with url_name='blog:post-list-by-tag' url_args=tag.slug %}
{% endblock content %}